### ISSUE TITLE
不走脑也要走点心

### ISSUE THREAD

**Issue by Manjioko** [lihuii/flask-bootstrap-docs-zh#1]
兄弟，翻译能走点心不？

**Comment by greyli** [comment]
对于文档翻译的质量，有下面几点说明：
- 这份文档是一年前翻译的，当时对很多概念还不是很熟悉，而且我的英语水平有限，对于其中的翻译错误，很抱歉为你带来不便。
- 我当时已在文档中加入了一篇[《翻译说明》](http://flask-bootstrap-zh.readthedocs.io/zh/latest/translate.html)，其中说明了这个情况：
> 这是我第一次翻译技术文档，里面难免会有一些小错误，欢迎指正或者到Github上提交修改。
- 这是一个开源项目，我发布出来的本意是能帮到其他人，同时也希望更多的人来维护和改进它。如果你发现了错误，可以修改然后提交PR。
- 同样因为这里一个开源项目，如果我有时间，我会去改进它；如果我没有时间，我也可以选择不去改进——这是我的自由。你不是我的老板或客户，我没有义务免费为你工作，也没有义务承担你的指责。

如果你走脑，走心的话，应该会发现这些。

但是你没有。
